import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import EmailInput from '../common/components/inputs/EmailInput/EmailInput.component';

const Home: NextPage = () => {
  const [email, setEmail] = useState('');

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-4xl text-pink-500">Hello World in the Pink!</h1>

      <EmailInput showTip emailState={email} handleInputChange={setEmail} />
    </div>
  );
};

export default Home;
